"""remove field S3File.bucket_name

Revision ID: 3accfa00217d
Revises: f60c60eac16a
Create Date: 2025-02-16 21:33:53.126303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3accfa00217d'
down_revision: Union[str, None] = 'f60c60eac16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s3_files', 'bucket_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_files', sa.Column('bucket_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
