"""update table exercises

Revision ID: 525f7331eec7
Revises: ce40bd7ecdb6
Create Date: 2025-04-11 16:00:27.068665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525f7331eec7'
down_revision: Union[str, None] = 'ce40bd7ecdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('source', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('module_id', sa.UUID(), nullable=True, comment='Module ID for the exercise'))
    op.alter_column('exercises', 'course_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key("exercises_module_id_fk", 'exercises', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.alter_column('lessons', 'order',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'order',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False)
    op.drop_constraint("exercises_module_id_fk", 'exercises', type_='foreignkey')
    op.alter_column('exercises', 'course_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('exercises', 'module_id')
    op.drop_column('exercises', 'source')
    # ### end Alembic commands ###
