"""update migration 20250401

Revision ID: 8d8078a54610
Revises: 8cda8491a5a0
Create Date: 2025-04-01 08:38:47.107229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8078a54610'
down_revision: Union[str, None] = '8cda8491a5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.alter_column('recommend_quiz_questions', 'difficulty',
        existing_type=sa.VARCHAR(),
        type_=sa.Enum('easy', 'medium', 'hard', name='difficultylevel'),
        existing_nullable=False,
        postgresql_using="difficulty::difficultylevel")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommend_quiz_questions', 'difficulty',
               existing_type=sa.Enum('easy', 'medium', 'hard', name='difficultylevel'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###
