"""Add relationship for quizzes

Revision ID: 3c0b0428b10f
Revises: 8cabff0e4b8e
Create Date: 2025-01-22 20:25:45.820474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0b0428b10f'
down_revision: Union[str, None] = '8cabff0e4b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
