"""Add new model: activities

Revision ID: 4524b5f89223
Revises: 69032b86f622
Create Date: 2024-11-20 15:30:25.804983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4524b5f89223'
down_revision: Union[str, None] = '69032b86f622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('VIEW_COURSE', 'RESUME_ACTIVITY', 'COMPLETE_LESSON', 'COMPLETE_ASSIGNMENT', 'ENROLL_COURSE', 'BADGE_EARNED', name='type'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('courses', 'status',
               existing_type=postgresql.ENUM('New', 'In Progress', 'Completed', name='statustype'),
               type_=sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', name='statustype'),
               existing_nullable=False,
               existing_server_default=sa.text("'New'::statustype"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('courses', 'status',
               existing_type=sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', name='statustype'),
               type_=postgresql.ENUM('New', 'In Progress', 'Completed', name='statustype'),
               existing_nullable=False,
               existing_server_default=sa.text("'New'::statustype"))
    op.drop_table('activities')
    # ### end Alembic commands ###
