"""Change password field

Revision ID: 52c257255b18
Revises: 195b70bd9e5c
Create Date: 2025-01-09 21:19:07.451332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c257255b18'
down_revision: Union[str, None] = '195b70bd9e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('professors', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('professors', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('admins', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
