"""Add information fields for user

Revision ID: 628b414eda2d
Revises: 9801a14226e2
Create Date: 2025-01-07 13:54:35.903053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628b414eda2d'
down_revision: Union[str, None] = '9801a14226e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('admins', sa.Column('fullname', sa.String(length=255), nullable=True))
    op.add_column('professors', sa.Column('mscb', sa.String(length=10), nullable=True))
    op.add_column('professors', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('professors', sa.Column('fullname', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('mssv', sa.String(length=10), nullable=True))
    op.add_column('students', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('fullname', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'fullname')
    op.drop_column('students', 'date_of_birth')
    op.drop_column('students', 'mssv')
    op.drop_column('professors', 'fullname')
    op.drop_column('professors', 'date_of_birth')
    op.drop_column('professors', 'mscb')
    op.drop_column('admins', 'fullname')
    op.drop_column('admins', 'date_of_birth')
    # ### end Alembic commands ###
