"""remove created_at/updated_at

Revision ID: 7aae9b134150
Revises: 4524b5f89223
Create Date: 2024-11-20 15:33:41.067310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aae9b134150'
down_revision: Union[str, None] = '4524b5f89223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the columns from the activities table
    op.drop_column('activities', 'created_at')
    op.drop_column('activities', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the columns back in case of rollback (optional)
    op.add_column('activities', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('activities', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###
