"""Delete foreign key relationship between lessons and exercises

Revision ID: 8cabff0e4b8e
Revises: d8fd7fd33e56
Create Date: 2025-01-22 20:22:41.690613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cabff0e4b8e'
down_revision: Union[str, None] = 'd8fd7fd33e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
