"""Add password fields

Revision ID: 9801a14226e2
Revises: ceb64b6b8901
Create Date: 2025-01-06 22:06:47.935786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9801a14226e2'
down_revision: Union[str, None] = 'ceb64b6b8901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('professors', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('students', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'password')
    op.drop_column('professors', 'password')
    op.drop_column('admins', 'password')
    # ### end Alembic commands ###
