"""move lesson type column from lessons table to student_lessons table 

Revision ID: 9e6ada106013
Revises: 5299e55c806c
Create Date: 2024-11-24 20:08:44.394209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e6ada106013'
down_revision: Union[str, None] = '5299e55c806c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'lesson_type')
    op.add_column('student_lessons', sa.Column('lesson_type', postgresql.ENUM(name="lessontype", create_type=False))),
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_lessons', 'lesson_type')
    op.add_column('lessons', sa.Column('lesson_type', postgresql.ENUM('original', 'recommended', name='lessontype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
