"""add relations between tables

Revision ID: ac261db49061
Revises: f76b6173d137
Create Date: 2024-11-21 20:07:56.506920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac261db49061'
down_revision: Union[str, None] = 'f76b6173d137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'type',
               existing_type=postgresql.ENUM('VIEW_COURSE', 'RESUME_ACTIVITY', 'COMPLETE_LESSON', 'COMPLETE_ASSIGNMENT', 'ENROLL_COURSE', 'BADGE_EARNED', name='type'),
               type_=sa.Enum('VIEW_COURSE', 'RESUME_ACTIVITY', 'COMPLETE_LESSON', 'COMPLETE_ASSIGNMENT', 'ENROLL_COURSE', 'BADGE_EARNED', name='activitytype'),
               existing_nullable=False)
    op.alter_column('exercises', 'status',
               existing_type=postgresql.ENUM('new', 'in_progress', 'completed', name='statustype'),
               nullable=False,
               existing_server_default=sa.text("'new'::statustype"))
    op.alter_column('lessons', 'status',
               existing_type=postgresql.ENUM('new', 'in_progress', 'completed', name='statustype'),
               nullable=False,
               existing_server_default=sa.text("'new'::statustype"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'status',
               existing_type=postgresql.ENUM('new', 'in_progress', 'completed', name='statustype'),
               nullable=True,
               existing_server_default=sa.text("'new'::statustype"))
    op.alter_column('exercises', 'status',
               existing_type=postgresql.ENUM('new', 'in_progress', 'completed', name='statustype'),
               nullable=True,
               existing_server_default=sa.text("'new'::statustype"))
    op.alter_column('activities', 'type',
               existing_type=sa.Enum('VIEW_COURSE', 'RESUME_ACTIVITY', 'COMPLETE_LESSON', 'COMPLETE_ASSIGNMENT', 'ENROLL_COURSE', 'BADGE_EARNED', name='activitytype'),
               type_=postgresql.ENUM('VIEW_COURSE', 'RESUME_ACTIVITY', 'COMPLETE_LESSON', 'COMPLETE_ASSIGNMENT', 'ENROLL_COURSE', 'BADGE_EARNED', name='type'),
               existing_nullable=False)
    # ### end Alembic commands ###
