"""add createdByAdminID

Revision ID: bc253897d435
Revises: 66304d04b364
Create Date: 2025-01-16 00:49:42.462005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc253897d435'
down_revision: Union[str, None] = '66304d04b364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('createdByAdminID', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'createdByAdminID')
    # ### end Alembic commands ###
