"""update delete policy for learning path and related tables

Revision ID: ce9d4d94836e
Revises: 191f795929ab
Create Date: 2025-01-21 04:21:14.791179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9d4d94836e'
down_revision: Union[str, None] = '191f795929ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_exercises_module_id_fkey', 'quiz_exercises', type_='foreignkey')
    op.create_foreign_key("quiz_module_id_fk", 'quiz_exercises', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('recommend_lessons_learning_path_id_fkey', 'recommend_lessons', type_='foreignkey')
    op.create_foreign_key("recommend_lesson_lp_fk", 'recommend_lessons', 'learning_paths', ['learning_path_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('modules_recommend_lesson_id_fkey', 'modules', type_='foreignkey')
    op.create_foreign_key("modules_recommend_lesson_id_fkey", 'modules', 'recommend_lessons', ['recommend_lesson_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("recommend_lesson_lp_fk", 'recommend_lessons', type_='foreignkey')
    op.create_foreign_key('recommend_lessons_learning_path_id_fkey', 'recommend_lessons', 'learning_paths', ['learning_path_id'], ['id'])
    op.drop_constraint("quiz_module_id_fk", 'quiz_exercises', type_='foreignkey')
    op.create_foreign_key('quiz_exercises_module_id_fkey', 'quiz_exercises', 'modules', ['module_id'], ['id'])
    op.drop_constraint("modules_recommend_lesson_id_fkey", 'modules', type_='foreignkey')
    op.create_foreign_key('modules_recommend_lesson_id_fkey', 'modules', 'recommend_lessons', ['recommend_lesson_id'], ['id'])
    # ### end Alembic commands ###
