"""Add email fields

Revision ID: ceb64b6b8901
Revises: cb6315430b27
Create Date: 2025-01-06 18:32:18.758403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb64b6b8901'
down_revision: Union[str, None] = 'cb6315430b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('admins', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('admins', sa.Column('verification_code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('admins', sa.Column('password_reset_code', sa.String(length=6), nullable=True))
    op.add_column('admins', sa.Column('password_reset_code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('admins', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('professors', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('professors', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('professors', sa.Column('verification_code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('professors', sa.Column('password_reset_code', sa.String(length=6), nullable=True))
    op.add_column('professors', sa.Column('password_reset_code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('professors', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('students', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('students', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('students', sa.Column('verification_code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('password_reset_code', sa.String(length=6), nullable=True))
    op.add_column('students', sa.Column('password_reset_code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_active')
    op.drop_column('students', 'password_reset_code_expires_at')
    op.drop_column('students', 'password_reset_code')
    op.drop_column('students', 'verification_code_expires_at')
    op.drop_column('students', 'verification_code')
    op.drop_column('students', 'is_email_verified')
    op.drop_column('professors', 'is_active')
    op.drop_column('professors', 'password_reset_code_expires_at')
    op.drop_column('professors', 'password_reset_code')
    op.drop_column('professors', 'verification_code_expires_at')
    op.drop_column('professors', 'verification_code')
    op.drop_column('professors', 'is_email_verified')
    op.drop_column('admins', 'is_active')
    op.drop_column('admins', 'password_reset_code_expires_at')
    op.drop_column('admins', 'password_reset_code')
    op.drop_column('admins', 'verification_code_expires_at')
    op.drop_column('admins', 'verification_code')
    op.drop_column('admins', 'is_email_verified')
    # ### end Alembic commands ###
