"""fix relation between student-exercises and exercises tables

Revision ID: df1bfc39d4cd
Revises: fafccea735bf
Create Date: 2024-11-22 15:12:20.247143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1bfc39d4cd'
down_revision: Union[str, None] = 'fafccea735bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
