"""Update tables

Revision ID: eba587699efd
Revises: 52c257255b18
Create Date: 2025-01-15 22:29:54.843707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eba587699efd'
down_revision: Union[str, None] = '52c257255b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('nCredit', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('nSemester', sa.Integer(), nullable=True))
    op.alter_column('student_courses', 'last_accessed',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('student_courses', 'completed_lessons',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_courses', 'time_spent',
               existing_type=postgresql.INTERVAL(),
               nullable=True)
    op.alter_column('student_courses', 'assignments_done',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_courses', 'assignments_done',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_courses', 'time_spent',
               existing_type=postgresql.INTERVAL(),
               nullable=False)
    op.alter_column('student_courses', 'completed_lessons',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_courses', 'last_accessed',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('courses', 'nSemester')
    op.drop_column('courses', 'nCredit')
    # ### end Alembic commands ###
