"""add relation student_exercises for exercises table

Revision ID: fafccea735bf
Revises: d65df0b4e017
Create Date: 2024-11-22 15:04:42.415577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fafccea735bf'
down_revision: Union[str, None] = 'd65df0b4e017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_exercises', 'status',
               existing_type=postgresql.ENUM('new', 'in_progress', 'completed', name='statustype'),
               nullable=False)
    op.alter_column('student_lessons', 'status',
               existing_type=postgresql.ENUM('new', 'in_progress', 'completed', name='statustype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_lessons', 'status',
               existing_type=postgresql.ENUM('new', 'in_progress', 'completed', name='statustype'),
               nullable=True)
    op.alter_column('student_exercises', 'status',
               existing_type=postgresql.ENUM('new', 'in_progress', 'completed', name='statustype'),
               nullable=True)
    # ### end Alembic commands ###
